### ISSUE TITLE
Not replacing misspelling when used in a webview

### ISSUE THREAD

**Issue by ccnokes** [paulcbetts/electron-spellchecker#12]
I have an app with multiple instances of webviews running in the same window because I like to party. 

I'm running electron-spellchecker inside each webview in a preload script, using the suggested implementation in the README. When I misspell a word, I don't see any spelling suggestions or red squigglies (no errors either). I do see copy, paste, etc. though. I've tried running with debug on and I don't see any errors from electron-spellchecker. 

I've also tried running it in the host renderer and passing the webview instance to `ContextMenuBuilder` and `ContextMenuListener` and that didn't work either. 

This is what my implementation looks like:
```typescript
const {SpellCheckHandler, ContextMenuListener, ContextMenuBuilder} = require('electron-spellchecker');

export default function () {
	let spellCheckHandler = (window as any).spellCheckHandler = new SpellCheckHandler();

	spellCheckHandler.attachToInput();
	spellCheckHandler.switchLanguage('en-US');

	let contextMenuBuilder = new ContextMenuBuilder(spellCheckHandler);
	let contextMenuListener = new ContextMenuListener((info) => {
		contextMenuBuilder.showPopupMenu(info);
	});
}
```

Interestingly when I modify the example to run it in a webview by adding `<webview src="./index.html" nodeIntegration></webview>` to the HTML, I do get red squigglies and spelling suggestions but when I click the suggestion the text is not replaced.

**Comment by paulcbetts** [comment]
Stupid question, you're actually calling that function right?

**Comment by ccnokes** [comment]
Yep. It gets required and invoked in a main preload script. I've set breakpoints in it and verified it gets called.

**Comment by ccnokes** [comment]
I can fork this repo with the broken example if you'd like.

**Comment by paulcbetts** [comment]
@ccnokes I'd add some console.logs to https://github.com/paulcbetts/electron-spellchecker/blob/master/src/spell-check-handler.js#L393 (don't add a breakpoint, Electron crashes) and try to see if it's getting called

**Comment by ccnokes** [comment]
That method is not getting called

**Comment by ccnokes** [comment]
That method is getting called. 

Here's what I logged:
```javascript
  handleElectronSpellCheck(text) {
    console.log(text, this.currentSpellchecker);
    if (!this.currentSpellchecker) return true;
    this.spellCheckInvoked.onNext(true);

    if (contractionMap[text.toLocaleLowerCase()]) return true;

    // NB: I'm not smart enough to fix this bug in Chromium's version of
    // Hunspell so I'm going to fix it here instead. Chromium Hunspell for
    // whatever reason marks the first word in a sentence as mispelled if it is
    // capitalized.
    let result = this.currentSpellchecker.checkSpelling(text);
    console.log(result);

    if (result.length < 1) return true;
    if (result[0].start !== 0) {
      this.spellingErrorOccurred.onNext(text);
      return false;
    }

    let ret = this.currentSpellchecker.isMisspelled(text.toLocaleLowerCase());
    if (ret) {
      this.spellingErrorOccurred.onNext(text);
    }

    console.log(ret);

    return !ret;
  }
```

The ouput for that is:
```
tessst <Spellchecker>  //seems to get called with the right text
{ end: 6, start: 0 } //not sure what this is
false //I'm assuming this should be true because "tessst" is misspelled? 
```

**Comment by ccnokes** [comment]
I think I figured out what was going on.

To get the webview in the example working, I passed in the `remote.getCurrentWebContents()` to `ContextMenuBuilder` like so:
```javascript
let contextMenuBuilder = new ContextMenuBuilder(window.spellCheckHandler, remote.getCurrentWebContents());
  let contextMenuListener = new ContextMenuListener(async (info) => {
    await contextMenuBuilder.showPopupMenu(info);
  });
```
For some reason that class does this `this.windowOrWebView = windowOrWebView || remote.getCurrentWindow();` when everything else does `this.windowOrWebView = windowOrWebView || remote.getCurrentWebContents();`. Is that a bug? The examples all work with that change. The tests don't work with or without on my machine ¯\_(ツ)_/¯. 

In my actual app where misspellings weren't getting squigglied, my best guess is that because I had another lib that was handling this functionality for me and it had a dependency on node-spellchecker that there was some kind of conflict going on? When I `npm uninstall`ed that lib and node-spellchecker, reinstalled electron-spellchecker, it worked.

**Comment by paulcbetts** [comment]
> For some reason that class does this this.windowOrWebView = windowOrWebView || remote.getCurrentWindow(); when everything else does this.windowOrWebView = windowOrWebView || remote.getCurrentWebContents();. Is that a bug?

I think there we actually need the window, not its webContents
