### ISSUE TITLE
Question on module size

### ISSUE THREAD

**Issue by akashnimare** [paulcbetts/electron-spellchecker#25]
@paulcbetts thanks for building this awesome spellchecker. It works great 😄 . I had one doubt regarding the size of this module. I'm using it [here](https://github.com/zulip/zulip-electron). After rebuilding using electron-rebuild and packaging the app I see the app size increases gradually. Later I found out it's because of the size of **node_modules/@paulcbetts** which is ~121 MB. Is this the normal size or I'm doing something wrong here 🤔

**Comment by akashnimare** [comment]
@felixrieseberg any idea about this?

**Comment by paulcbetts** [comment]
You need to strip some junk out of `cld2` afaik, use a tool like WinDirStat and look for folders you don't need to actually ship, and remove it in your build process

**Comment by akashnimare** [comment]
Thanks a lot :)

**Comment by akashnimare** [comment]
@paulcbetts  The problem lies in node_modules/@paulcbetts/cld/deps/**cld** directory which is of ~116 MB. I deleted it and now it's working fine. Should I expect any side effects of removing this folder ?

**Comment by paulcbetts** [comment]
@akashnimare Nope

**Comment by Sukram21** [comment]
Related issue on excluding this folder while packaging (using electron-builder): https://github.com/electron-userland/electron-builder/issues/927

**Comment by edmoresamewave** [comment]
@paulcbetts what are the implications of excluding the entire `@paulcbetts/cld` folder? Even after stripping out the `cld\deps\cld` folder it still adds 33MB.
