### ISSUE TITLE
 Cannot find module 'debug/browser'

### ISSUE THREAD

**Issue by beljand** [paulcbetts/electron-spellchecker#33]
I'm using MacOS, Node 6.5.0, Electron 1.4.6, Webpack 1 and Typescirpt. When I try to import the plugin, I get an error that _debug/browser_ module is missing. This error accrues only when app is bundled to .app, not when I run `electron app`.  Any ideas?

`module.js:457 Uncaught Error: Cannot find module 'debug/browser'
at Module._resolveFilename (module.js:455:15)
....`

**This was resolved with version 0.7.1**

**Comment by beljand** [comment]
Using v0.7.1 

`fs.js:640 Uncaught Error: ENOENT: no such file or directory, open '/Users/user/project/dist/mac/4th Office.app/Contents/Resources/app.asar.unpacked/node_modules/spawn-rx/lib/index.js'`

I got this error in dev console, but only in a packed application. If I start the app with _electron_ everything works fine.

**Comment by paulcbetts** [comment]
@beljand Jobber is only used on Windows, on macOS process groups work properly :) 

Why is spawn-rx being searched for in the unpacked part of the ASAR archive?

**Comment by beljand** [comment]
For the purpose of testing I have disabled `asar`, now packaging works for MacOS, but not for Linux/Win builds

`keyboard-layout@2.0.7 install /project/node_modules/keyboard-layout
node-gyp rebuild
make: Entering directory '/project/node_modules/keyboard-layout/build'
  CXX(target) Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o
In file included from ../src/keyboard-layout-manager-linux.cc:1:0:
../src/keyboard-layout-manager.h:7:22: fatal error: X11/Xlib.h: No such file or directory
compilation terminated.
keyboard-layout-manager.target.mk:96: recipe for target 'Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o' failed
make: *** [Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o] Error 1
make: Leaving directory '/project/node_modules/keyboard-layout/build'`

**Comment by paulcbetts** [comment]
You're missing libxkbfile-dev. These are all separate issues, so maybe open them separately?
