### ISSUE TITLE
Issue with asar.unpacked with electron-builder

### ISSUE THREAD

**Issue by beljand** [paulcbetts/electron-spellchecker#34]
When using _electron-builder_, spawn-rx gets copied into app.asar.unpacked, but not all files are copied, resulting in 

`Uncaught Error: ENOENT: no such file or directory, open  ../app.asar.unpacked/node_modules/spawn-rx/lib/index.js`

Not sure if this is a electron-spellchecker, or electron-builder issue.

**Comment by paulcbetts** [comment]
electron-spellchecker has no control over packaging, please take this to electron-builder (actually, let me recommend https://github.com/electron-userland/electron-forge instead, it's very new but it's going to be The Supported Way To Package) and it does a lot of cool stuff
